export default {
  media: {
    title: 'Media Library',
    description: 'Preview and manage images and videos generated by the Creative Center and persisted to object storage (R2/S3).',
    bucket: 'Bucket',
    total: '{count} item(s)',
    tabs: {
      all: 'All',
      image: 'Images',
      video: 'Videos'
    },
    refresh: 'Refresh',
    loading: 'Loading…',
    loadMore: 'Load more',
    loadingMore: 'Loading…',
    empty: 'No generated assets in this category',
    fields: {
      kind: 'Type',
      size: 'Size',
      modifiedAt: 'Created at',
      key: 'Object key'
    },
    kind: {
      image: 'Image',
      video: 'Video',
      other: 'Other'
    },
    actions: {
      open: 'Open in new tab',
      download: 'Download',
      delete: 'Delete'
    },
    preview: {
      title: 'Preview'
    },
    deleteConfirm: 'Delete this object? The file in object storage will be removed permanently and cannot be restored.',
    deleted: 'Deleted',
    deleteFailed: 'Delete failed',
    loadFailed: 'Failed to load the media library',
    unavailable: {
      title: 'Object storage is disabled or not fully configured',
      description: 'The media library requires enabled, fully configured object storage. Configure and enable async image object storage under Backup & Storage first.',
      goConfigure: 'Go to configuration'
    }
  }
}
